### ISSUE TITLE
Duplicate player names

### ISSUE THREAD

**Issue by jbaack** [bradleycwojcik/euchre-cli#48]
Got duplicate player names on one run. I think this change in unique_cpu_name() in util.py will fix it

if name.lower() not in taken_names:

**Comment by boldandbrad** [comment]
Thank you for catching this! I will implement the change in the next patch. I hope you are enjoying the game, any other feedback submitted as issues is greatly appreciated :)

**Comment by boldandbrad** [comment]
Released in v0.6.1. Thanks again!
